/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
}


function gotoProfile(event)
{
    hideAllContent();
    document.getElementById('profileContent').style.display = "block";
    navigate("Profile");
}


function gotoPortfolio(event)
{
    hideAllContent();
    document.getElementById('portfolioStack').style.display = "block";
    navigate("Portfolio");
}


function gotoResume(event)
{
    hideAllContent();
    document.getElementById('resumeContent').style.display = "block";
    navigate("Resume");
}


function gotoLinks(event)
{
    hideAllContent();
    document.getElementById('linksContent').style.display = "block";
    navigate("Links");

}


function navigate(name) {
    var browser = document.getElementById("browser").object;
    browser.goForward(document.getElementById('detail'), "My "+name);
}

function hideAllContent() {
    document.getElementById('profileContent').style.display = "none";
    document.getElementById("resumeContent").style.display = "none";
    document.getElementById('portfolioStack').style.display = "none";
    document.getElementById('linksContent').style.display = "none";
}


function gotoProject(event)
{
    alert("test");
}


function emailMe(event)
{
    location.replace("mailto:holevietlong@gmail.com?subject=Comments on your personal website");
}


function gotoLink(event)
{
    // Insert Code Here
}
